### ISSUE TITLE
New phenotype for zebrafish

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#113]
Hi,

Could you please add the following two phenotypes to the controlled terms?
- low aggression
- high aggression
These phenotypes are for a dataset with zebrafish and this is the most differentiating characteristic between two groups. It is also important for the research objective, so it would be great to visualise this at the level of the subjects

Many thanks,
Maaike

**Comment by UlrikeS91** [comment]
That won't be possible since the CT/phenotype is deprecated. Since you mentioned the case to me offline, I'll have a look and see what other solutions could apply for this case.

**Comment by UlrikeS91** [comment]
This is actually a rather interesting and could potentially be solve using the core strain schema. 

A rough summary of the use case: 
They did RNA sequencing to identify whether or not mirror aggression behavior has any genetic markers is zebrafish. To do so, they selectively bred fish displaying highest aggression or lowest aggression behavior for 4 generations (always selecting the offspring with highest/lowest for the next generation). 

Generally, zebrafish do have strains that commonly are stated - in this case "AB wild-type". So, the subjects receive a strain either way. 
Something like this:
property | value
---|---
backgroundStrain | -
breedingType | inbred
description | A zebrafish line derived from the mating of two lines, A and B, in Albany, Oregon in the early 1970s. The current AB stock is maintained through large group spawning crosses. 
diseaseModel | - 
geneticStrainType* | wildtype
identifier | -
laboratoyCode | -
name* | AB
ontologyIdentifier | - 
phenotype | -
RRID | - 
species | danio rerio
stockNumber | -

The wildtype strain itself should get any specific phenotype since the aggression behavior is present in all of them. The researchers selected for specific levels of aggression from this wildtype population and bred those. So, we could add two additional strains that reflect this selective breeding highly aggressive and little to non-aggressive animals.   

property | highly aggressive | non-aggressive | Notes
---|---|---|---
backgroundStrain | AB | AB | -
breedingType | selective (in)breeding? | selective (in)breeding? | We would need to add this as a CT, it would be best suitable. Not sure if "inbreeding" is necessary.
description | A zebrafish line that was bred by selectively mating animals displaying high mirror aggression behavior for four generations, each generation selecting the most aggressive animals to produce the next generation offspring. | A zebrafish line that was bred by selectively mating animals displaying low mirror aggression behavior for four generations, each generation selecting the least aggressive animals to produce the following offspring. | -  
diseaseModel | - | - | -
geneticStrainType* | wildtype? | wildtype? | I'm not sure here. Wildtype isn't wrong but I don't believe that it's quite right either.
identifier | - | - | -
laboratoyCode | - | - | -
name* | HAZ (AB background) | LAZ (AB background) | aka "high/low mirror aggression zebrafish with AB background" 
ontologyIdentifier | - | - | -
phenotype | high mirror aggression behavior | low mirror aggression behavior | -
RRID | -  | -  | -
species | danio rerio | danio rerio  | -
stockNumber | - | -  | -

Any thoughts, @MaaikevS, @lzehl, @tgbugs and @Majpuc?

**Comment by lzehl** [comment]
I'd leave this to @tgbugs and @Majpuc to discuss. Sounds like a good idea to me. @tgbugs do you know some zebrafish experts that could be included into the discussion?

**Comment by Majpuc** [comment]
It seems from the literature that for Zebrafish, the term Wild type encompasses several strains, like AB, Tübingen long fin (TL), and Wild Indian Karyotype (WIK) (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7465594/). So when you are crossing AB only, you select for some genes but the strain logically should remain AB. I suggest to ask the DP as they are specialists in that matter.

**Comment by MaaikevS** [comment]
@Majpuc this seems like a logical explanation and I agree that the background would be AB. What is it exactly that you want clarification of from the DP?
I would be keen to move forward with this as he is aiming to release the dataset at the end of February and it would be nice to have this in place (if possible)

**Comment by Majpuc** [comment]
What I mean is that the Zebrafish community seems to have slightly different conventions compared to Rodent community for naming subjects created by crossing different lines. I suggest to get some insight from the DP if they are willing to answer a few questions, so we don't impose a naming convention that is not relevant or make wrong assumptions. If they could give us some typical examples, it could be useful.

**Comment by UlrikeS91** [comment]
@Majpuc thank you for your input on this. 

> It seems from the literature that for Zebrafish, the term Wild type encompasses several strains, like AB, Tübingen long fin (TL), and Wild Indian Karyotype (WIK) (see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7465594/). So when you are crossing AB only, you select for some genes but the strain logically should remain AB. I suggest to ask the DP as they are specialists in that matter.

I get what you mean and I think I mostly agree that AB is still the strain. That is the reason that I proposed "selective (in)breeding" as breeding type. The issue is the phenotype vs. genotype. They select for specific phenotypes hoping that the resulting offsprings in fact displays differences in their genotypes (compared to both the normal AB strain and to the other selected phenotype). That means that if the genotype is in fact different, they qualify as new strains, but if not, they don't :D 

@MaaikevS, you could send the data provider the proposed solution and see what they say. If they think that this solution is not appropriate, you could ask for details/ways to improve it. I do agree with @majpuc that they clearly will know more about zebrafish (strains) compared to any of us since they are actually working with them. So, involving them in the decision making would be smart.
If they do approve the proposal, you either need to let me know so that I can create missing controlledTerms (e.g. "selectively inbred") or you prepare a pull request with the missing controlledTerms yourself 😉

**Comment by MaaikevS** [comment]
I asked the DP and he said that the fish have been derived from AB wildtype zebrafish. So the genetic strain type should be wildtype according to him. He said that the phenotype between the groups differ, but that is accounted for in your diagram and despite the difference in aggression they both have a AB genetic background

**Comment by UlrikeS91** [comment]
> I asked the DP and he said that the fish have been derived from AB wildtype zebrafish. So the genetic strain type should be wildtype according to him. He said that the phenotype between the groups differ, but that is accounted for in your diagram and despite the difference in aggression they both have a AB genetic background

Sound pretty much exactly like what I propose, right? Then would you like to add the missing controlled terms yourself, or should I? 😉

**Comment by MaaikevS** [comment]
Indeed, it is like you proposed. I would be happy to move forward with that and add the missing controlled terms

**Comment by UlrikeS91** [comment]
Cool! When you are ready with your PR, you can set me as reviewer.

**Comment by MaaikevS** [comment]
Ok, I entered the strains into the system and created a new CT for selective inbreeding ( which was accidentally pulled together with the other pull request, so apologies)
