### ISSUE TITLE
cell types needed for Models migration

### ISSUE THREAD

**Issue by apdavison** [HumanBrainProject/openMINDS_controlledTerms#119]
The following cell types are needed for the Model migration that are not in the KG.

The names don't have to match these exactly, I can do a mapping if there is an entry in Interlex/Scicrunch for the same cell type but with a slightly different name.

- Golgi cell
- L2/3 pyramidal cell
- L5 tufted pyramidal cell
- cerebellar granule cell
- cholinergic interneuron
- fast spiking interneuron
- hippocampus CA1 pyramidal cell
- medium spiny neuron
- medium spiny neuron (D1 type)
- medium spiny neuron (D2 type)

**Comment by UlrikeS91** [comment]
Thanks for the request, @apdavison. For cell types, we struggle a little bit with finding the correct ontology IDs because they tend to be more specific than what is colloquially used. Could you please have a look at the list below and see if this will cover want you need.

requested cell type | existing controlled term | suggested name | InterLex | comment
--|--|--|--|--
Golgi cell |  | **_cerebellum_** Golgi cell | http://uri.interlex.org/base/ilx_0101966 | 
L2/3 pyramidal cell |  | **_neocortex_** layer 2/3 pyramidal neuron | http://uri.interlex.org/base/ilx_0107387 |  
L5 tufted pyramidal cell |  | **_neocortex_** layer 5 tufted pyramidal neuron | http://uri.interlex.org/ilx_0738209 |  
cerebellar granule cell |  | cerebellum granule neuron | http://uri.interlex.org/ilx_0101967 |  
cholinergic interneuron |  | **_neostriatum_** cholinergic interneuron | http://uri.interlex.org/ilx_0107403 | will this cover all your use cases?
fast spiking interneuron |  |  |  | can't find this in InterLex; I know that most of them are PV+ (GABAergic) interneurons, but not all, right? If not, we should add this term 
hippocampus CA1 pyramidal cell |  | hippocampus CA1 pyramidal neuron | http://uri.interlex.org/base/ilx_0105031 | 
medium spiny neuron |  | **_striatum_** medium spiny neuron | http://uri.interlex.org/ilx_0784362 | will this cover all your use cases?
medium spiny neuron (D1 type) | neostriatum direct pathway spiny neuron |  | http://uri.interlex.org/ilx_0107404 | we had a similar request here: #94; will this cover all your use cases? 
medium spiny neuron (D2 type) | neostriatum indirect pathway spiny neuron |  | http://uri.interlex.org/ilx_0107405 | we had a similar request here: #94; will this cover all your use cases?
 

@tgbugs and @lzehl, happy to get your thoughts on this too.

**Comment by apdavison** [comment]
Many thanks @UlrikeS91. I think all of your proposals are good.

"neostriatum cholinergic interneuron" is probably ok for the Models we have, but it would be good to add the more general term as well, as I believe cholinergic interneurons are also found in the cerebral cortex, hippocampus, and nucleus accumbens, as well as the striatum.

"fast spiking interneuron" is a widely used term, so I agree we should add it. It seems all such neurons are parvalbumin-positive, but not all parvalbumin-positive interneurons are fast-spiking (e.g. https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3602937/)
