### ISSUE TITLE
Add new units of measurements

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#134]
I am working on protocol executions etc and I am missing some important units. 

I am listing the ones I came across (and that might be useful to add) below:
- % w/v
- mg/kg
- percent
- ug/ml
- um/ml
- ml/g
- mg/ml
- degrees celsius
- mM

@lzehl @UlrikeS91 There are many additional options of course, but please let me know if we can add (some of) these. Again, I am happy to make the instances if you can tell me which ones to add and how we should name them.

Thanks!

**Comment by lzehl** [comment]
@MaaikevS thank you for this issue. This brings up a general question on SI vs non-SI units (which we did not distinguish so far) and how to deal with combinations of units as result of formulas (e.g. fraction calculations).

@apdavison I'd like to hear your thoughts here. Should we substructure the unit of measurements?

**Comment by apdavison** [comment]
> Should we substructure the unit of measurements?

I think that would be adding too much complexity for too little return. 

We should certainly avoid non-SI units except where they are the norm for a field, but not too many neuroscientists are using pounds, inches or furlongs these days :-)

**Comment by lzehl** [comment]
@apdavison any comments on @MaaikevS suggestions or can we just add them as they are?

**Comment by lzehl** [comment]
@MaaikevS if we register them they should be registered under their full names to be consistent with the others. Abbreviations can be put into synonyms (for now).

**Comment by apdavison** [comment]
As long as the non-standard one has a clear definition (I don't know what `% w/v` is) I'm fine with adding these.

**Comment by lzehl** [comment]
:joy: I had to look up that one as well... @MaaikevS do you want to make the respective PR or should we take over?

**Comment by MaaikevS** [comment]
Regarding the % w/v, this is not very consistently used by data providers or described in methods. For example some people would say 20 % v/w sucrose solutions, whereas othere would just say 20% sucrose solution. In other words, not sure how important that particular one is.

I can make the instances.

**Comment by UlrikeS91** [comment]
> Regarding the % w/v, this is not very consistently used by data providers or described in methods. For example some people would say 20 % v/w sucrose solutions, whereas othere would just say 20% sucrose solution. In other words, not sure how important that particular one is.
> 
> I can make the instances.

The weight/volume percentage concentration (% w/v) is a standard way of reporting concentrations. I've used it both in the chemical lab and biological lab. It means that a solid (w as in weight, sometimes also m as in mass instead of the w) has been mixed with a liquid (v as in volume). For your example, it means that 20 g sucrose have been solved in 100 mL of something (in relation to cryoblocking, it's typically PBS or some other buffer). The notion "20% sucrose solution" is what people tend to say/write assuming people know that sucrose is a solid. So, for such common things the details are often dropped, but the "w/v" gives information about what has been mixed without knowing the substances.

This percentage concentration exists for the other two combinations as well: 
liquid with liquid: volume/volume percentage concentration (% v/v)
solid with solid: weight/weight percentage concentration (%w/w or % m/m)

Here are my thoughts to the list:

> * % w/v

Discussed above. I would vote for adding it (and the other 2).

> * mg/kg

This is a mean one. I assume you came across this in relation to the administration of anesthesia - meaning X milligram of the anesthetic were administered per kilogram weight of the subject. Typically, this is not a concentration in itself. The anesthetic is usually dilute in something, which has a concentration. The mg/kg just give you the target amount of the anesthetic that is supposed to be administered. In a way it's the concentration in the body of the subject, but then the unit would need to reflect that somehow for this special case (e.g. mg/kg body weight). 
I supposed mg/kg could describe other weight proportions, but I doubt that the second weight would typically be associated with tissue. Rather with e.g. an alloy were a specific metal portion could be described using mg/kg (similar to the % w/w).  

> * percent
> * ug/ml

No objection. Just needs to be written out as @lzehl already said.

> * um/ml

I'm not sure what this is. For me, "m" stands for "meter" and the "u" for "micro". Is this really supposed to be "micrometer per milliliter"? That seems odd...
 
> * ml/g

This might be related to "mg/kg". In which context has this been used? I'm not aware of a single concentration were this would be used to state the concentration of a mixture of a solid with a liquid. For such mixtures, it's always solid/mass per liquid/volume. 

> * mg/ml
> * degrees celsius

No objections.

> * mM

Here we should consider how this should be added. Molar is the abbreviation/common name for a SI unit - mol x m^-3 (which is mol/L). It's not a question of not adding it, it's just a question of which one being the name and which the synonyms. Additionally, we should add molar (M) and down to at least micromolar (uM) or even nanomolar (nM).

**Comment by MaaikevS** [comment]
Thanks you all for the comments.

The list is indeed not an exhaustive list, it is only based on units I came across whilst looking into the metadata.

Based on the comments above, I suggest adding the following:
- % w/v --> weightPerVolumePercentage.jsonld
- % v/v --> volumePerVolumePercentage.jsonld
- % w/w --> weightPerWeightPercentage.jsonld
- percent --> percent.jsonld
- ug/ml --> microgramPerMilliliter.jsonld
- mg/ml --> milligramPerMilliliter.jsonld
- degrees celsius ---> degreesCelsius.jsonld
- degrees --> degrees.jsonld (for angles etc)

For the molar related concentrations, I prefer to stick to the common name and add the SI unit in the synonyms because that will make it easier for people to use):
- mM --> millimolar.jsonld ( synonym: 10^-3 mol/L, mol/m^3)
- M --> molar.jsonld (synonym: mol/L, 10^3 mol/m^3)
- uM --> micromolar.jsonld (synonym: 10^-6 mol/L, 10^-3 mol/m^3)
- nM --> nanomolar.jsonld (synonym: 10^-9 mol/L, 10^-6 mol/m^3)

**Special cases (needs to be decided on)**: Very common way of describing the amount of a substance that is administered. It is important to add something for this somewhere, since this is a very important (maybe even the most important) piece of metadata to include for substance administration. 
- mg/kg

@lzehl @UlrikeS91 Please let me know if you are happy with these and their proposed names, so that I can create these instances.

**Comment by UlrikeS91** [comment]
Sounds good to me. I would also have used molar as the naming term. But stick to the singular for the units. So, use "degree" and not "degrees"

Still want to know what the um/ml is about, but it's not important for this here 😆 

I got a little too stuck on concentrations, but you are right that this is an important unit of measurement for substance administration. Maybe it could be solve by making the term very explicit: 
mg/kg body weight --> millgramPerKilogramBodyWeight.jsonld

**Comment by UlrikeS91** [comment]
The PR form @MaaikevS has been merged. I will close this issue for now.
