### ISSUE TITLE
Reassessing cellType - neuron vs cell

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#149]
@lzehl @UlrikeS91 We briefly talked about the naming convention of cell types offline. The thought was that we should use "neuron" if it can only be a neuron, otherwise "cell". It looks like there were some inconsistencies introduced in the past. Would this be something to clean up now (before adding more)?

This is the list we have at the moment:

astrocyte
**basket cell**
cerebellar   interneuron
**cerebellum   basket cell
**cerebellum   Golgi cell**
cerebellum   granule cell**
cerebellum   stellate neuron
**cholecystokinin   expressing cell**
cholinergic   interneuron
cholinergic   neuron
**cortical   basket cell**
cortical   interneuron
**D1 receptor   expressing cell**
dopaminergic   neuron
fast spiking   interneuron
**glial cell**
**granule cell**
hippocampus   CA1 pyramidal neuron
interneuron
**macroglial   cell
microglial   cell**
motor neuron
neocortex   layer 2/3 pyramidal neuron
neocortex   layer 5 tufted pyramidal neuron
neostriatum   cholinergic interneuron
neostriatum   direct pathway spiny neuron
neostriatum   indirect pathway spiny neuron
neuron
**parvalbumin   expressing cell**
**Purkinje   cell
pyramidal   cell**
sensory   neuron
**somatostatin   expressing cell**
spinal   interneuron
spiny neuron
stellate   neuron
striatal   interneuron
striatum   medium spiny neuron
**vascular   endothelial cell
vascular   smooth muscle cell**
**vasoactive-intestinal peptide expressing cell**

I would say, the following ones are the most relevant. If you want to keep it the way it is, then I feel that any new cell types should also have the name "cell" instead of "neuron":

cholecystokinin   expressing cell
D1 receptor   expressing cell
parvalbumin   expressing cell
somatostatin   expressing cell
vasoactive-intestinal peptide expressing cell

**Comment by apdavison** [comment]
For the main label, I think we should go with the most commonly used name. For example, when I Google "Purkinje cell" (with the quotes) I get 955'000 results, but "Purkinje neuron" gives only 75'500 results. Of course we can and should put the synonyms in as well.

**Comment by UlrikeS91** [comment]
Thanks, @MaaikevS for the very nice groundwork ☺️ This makes it a lot easier to discuss this topic.

> For the main label, I think we should go with the most commonly used name. For example, when I Google "Purkinje cell" (with the quotes) I get 955'000 results, but "Purkinje neuron" gives only 75'500 results. Of course we can and should put the synonyms in as well.

Thanks for your insights here. I agree. Some of the cell types listed here basically don't exist as "neuron", e.g. "granule cell" and of course @apdavison example. 

We should however prefer "neuron" over "cell" whenever there is no clear tendency (but a neuron is meant). So, @MaaikevS, all "XX-expressing cell" should be changed to "XX-expressing neuron". It will also make it more explicit and detailed, since I'm pretty sure that all our use cases mean exactly that and not other non-neuronal cells expressing a certain protein.

@lzehl commented in the PR openMetadataInitiative/openMINDS_controlledTerms#150 that she would like to avoid semantic combinations of brain regions and cell types (e.g. cortical neuron). But I would disagree. We do not have an unambiguous way of stating the combination of brain region + (generic) cell type and the location of the cell in the brain has an impact on the e.g. the cell's function and morphology. Even for cell types that only exist in a single brain region, it might be nice to add the brain region because not everybody just has this intrinsic knowledge about every cell type - myself included. Adding cell type instances is actually challenging for me in relation to that. The time that I had to spent to figure out whether or not a specific cell type only exists in one place or not, is pretty absurd... Also not entirely irrelevant: This is also how they are registered in InterLex. The generic types basically don't exist there (e.g. granule cell again: https://neuinfo.org/interlex/search?q=granule+cell). It still makes sense for us to add the generic types, but I would not remove the combinations. 

I merged the requested cell types from PR openMetadataInitiative/openMINDS_controlledTerms#150 into the list below. I reorganized them to have similar ones closer to each other and added my suggested changes (and synonyms).  


existing term | suggested change | InterLex
-- | -- | --
GENERIC
astrocyte | | [http://uri.interlex.org/ilx_0100947](http://uri.interlex.org/base/ilx_0100947)
basket cell | | 
glial cell | | [http://uri.interlex.org/ilx_0104634](http://uri.interlex.org/base/ilx_0104634)
granule cell | | 
interneuron | | [http://uri.interlex.org/ilx_0105593](http://uri.interlex.org/base/ilx_0105593) | 
macroglial cell | | [http://uri.interlex.org/ilx_0106438](http://uri.interlex.org/base/ilx_0106438) | 
microglial cell | | [http://uri.interlex.org/ilx_0106919](http://uri.interlex.org/base/ilx_0106919) | 
motor neuron | | [http://uri.interlex.org/ilx_0107122](http://uri.interlex.org/base/ilx_0107122) | 
neuron | | [http://uri.interlex.org/ilx_0107497](http://uri.interlex.org/base/ilx_0107497) | 
Purkinje cell | cerebellum Purkinje cell | [http://uri.interlex.org/ilx_0101974](http://uri.interlex.org/base/ilx_0101974) 
pyramidal cell | pyramidal neuron |
sensory neuron | | [http://uri.interlex.org/ilx_0110495](http://uri.interlex.org/base/ilx_0110495) | 
spiny neuron | | 
stellate neuron | | 
excitatory neuron | | 
inhibitory neuron | | 
WITH ANATOMICAL REGION
cerebellar interneuron | |
cerebellum basket cell | cerebellar basket cell| [http://uri.interlex.org/ilx_0101964](http://uri.interlex.org/base/ilx_0101964) 
cerebellum Golgi cell | cerebellar Golgi cell| [http://uri.interlex.org/ilx_0101966](http://uri.interlex.org/base/ilx_0101966) 
cerebellum granule cell | cerebellar granule cell | [http://uri.interlex.org/ilx_0101967](http://uri.interlex.org/base/ilx_0101967)
cerebellum stellate neuron | cerebellar stellate neuron | [http://uri.interlex.org/ilx_0101975](http://uri.interlex.org/base/ilx_0101975)
cortical basket cell | cortical basket cell | [http://uri.interlex.org/ilx_0107351](http://uri.interlex.org/base/ilx_0107351)
cortical interneuron | cortical interneuron | 
hippocampus CA1 pyramidal neuron | hippocampal CA1 pyramidal neuron | [http://uri.interlex.org/ilx_0105031](http://uri.interlex.org/base/ilx_0105031)
neocortex layer 2/3 pyramidal neuron | cortical layer 2/3 pyramidal neuron | [http://uri.interlex.org/ilx_0107387](http://uri.interlex.org/base/ilx_0107387)
neocortex layer 5 tufted pyramidal neuron | cortical layer 5 tufted pyramidal neuron | [http://uri.interlex.org/ilx_0738209](http://uri.interlex.org/base/ilx_07380209)
neostriatum cholinergic interneuron | striatal cholinergic interneuron | [http://uri.interlex.org/ilx_0107403](http://uri.interlex.org/ilx_0107403)
neostriatum direct pathway spiny neuron | striatal direct pathway spiny neuron | [http://uri.interlex.org/ilx_0107404](http://uri.interlex.org/ilx_0107404)
neostriatum indirect pathway spiny neuron | striatal indirect pathway spiny neuron | [http://uri.interlex.org/ilx_0107405](http://uri.interlex.org/ilx_0107405)
spinal interneuron | | 
striatal interneuron | | 
striatum medium spiny neuron | striatal medium spiny neuron | [http://uri.interlex.org/ilx_0784362](http://uri.interlex.org/ilx_0784362)
cortical neuron | cortical neuron |  
layer 6 neuron | cortical layer 6 neuron | 
hippocampal neuron | hippocampal neuron | 
XX-EXPRESSING
cholecystokinin expressing cell | cholecystokinin expressing neuron | 
D1 receptor expressing cell | D1 receptor expressing neuron | 
parvalbumin expressing cell | parvalbumin expressing neuron | 
somatostatin expressing cell | somatostatin expressing neuron | 
vasoactive-intestinal peptide expressing cell | vasoactive-intestinal peptide expressing neuron | 
aromatase expressing neuron | | 
calbindin expressing neuron | | 
calretinin expressing neuron | | 
choline acetyltransferase expressing neuron | | 
D2 receptor expressing neuron | | 
neuropeptide Y expressing neuron | | 
nitric oxide synthase expressing neuron | | 
-ERGIC
cholinergic interneuron | | [http://uri.interlex.org/ilx_0784333](http://uri.interlex.org/base/ilx_0784333)
cholinergic neuron | | 
dopaminergic neuron | | [http://uri.interlex.org/ilx_0103395](http://uri.interlex.org/base/ilx_0103395)
FUNCTIONAL DIFF.
fast spiking interneuron | | 
NON-NEURONAL
vascular endothelial cell | | [http://uri.interlex.org/ilx_0112265](http://uri.interlex.org/ilx_0112265)
vascular smooth muscle cell | | 
OTHERS
cortical postmitotic cell | cortical postmitotic neuron? | 
cortical progenitor cell | << not a neuron yet >> | 


General preferences in this proposal:
- cell == neuron: "neuron" preferred over "cell" if both are used equally 
- cell == neuron: "cell" preferred if this is more often used than "neuron"
- cell != neuron: obviously "cell"

- brain regions: e.g. cerebellar/cortical/striatal preferred over cerebellum/neocortex/(neo)striatum
- brain regions: preferably included, but generic ones may exist too

- XX - expressing cells: protein preferably same name as used for the corresponding molecular entity (e.g. D1 receptor)
- XX - expressing cells: written as "XX expressing neuron" (no "-" between protein and expressing)

**Comment by lzehl** [comment]
@UlrikeS91 I worry about the combination of terms (cell type + brain region) because it infers that there is something very special about this neuron type compared to the same neuron type in other regions which is not always the case (even if they are used as terms in the community). And we don't have the knowledge to research if the combination is valid and deserves its own term or not. Even if we say we don't care, where do you stop combining? For me this is a bottomless pit which we should solve in a better way. 

In my opinion: If we need non-ambiguous combinations of brain regions and cell types we should create a small schema that allows for this (UBERON parcellation + cell type). Although as study target combination (on a protocol execution) this should actually be non-ambiguous already. 

Nonetheless we can later come back to the issue and now do not touch this topic. If we discuss this further we anyway should meet with experts in the field to get a better insight.

**Comment by MaaikevS** [comment]
I agree with Lyuba's observation that brain region + cell type give the impression that the cell type is different, which may not always be the case. In some cases the cell type only/predominantly exists in a particular brain region, so in those cases one could argue that it is fine to use the combination. Nevertheless, it might be a good idea to put the cell types that fall into that category ("with anatomical region" on hold until we can consult some experts.

I would propose to proceed with the other changes though.
- add new cell types (from the other categories in Ulrike's table) following the new naming convention
- change the naming convention of existing terms (in conjunction with the KG)

I would be happy to start working on this so that we can also continue with the clean up of the term suggestion.
@UlrikeS91 @lzehl Would this work for you too?

**Comment by UlrikeS91** [comment]
I see your points and generally agree. I also like the suggestion to add a small schema to state such relations more clearly. I don't have any experience as to whether or not this would be problematic on the protocolExecution schema at the moment, but I suspect that some could in fact turn out to be ambiguous. But as long as we haven't experienced any issue, it should be fine to remove the brain regions from the cell types. 

Either way, I support @MaaikevS suggestion to proceed with some parts of the clean up already. If @lzehl is fine with my proposed naming convention (excluding the brain region stuff), then we could already implement those changes. More importantly, also add new cell types without introducing more chaos. @MaaikevS already suggested new cell types and more may come, so we cannot avoid adding new instances until we have reached a complete conclusion.

**Comment by lzehl** [comment]
@UlrikeS91 and @MaaikevS the suggested naming convention (excluding the brain region combination) seemed fine to me. @MaaikevS I agree with your approach.

**Comment by MaaikevS** [comment]
@lzehl @UlrikeS91 I made the changes as suggested. Once these changes are approved, I will clean up the term suggestions

**Comment by lzehl** [comment]
open TODOs are commented in:
https://github.com/HumanBrainProject/openMINDS_controlledTerms/issues/257
