### ISSUE TITLE
New cell types (based on term suggestions)

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#150]
Based on the term suggestions, there is a number of cell tyes that we should consider adding:

aromatase expressing neuron
calbindin expressing neuron
calretinin expressing neuron
choline acetyltransferase expressing neuron
cortical neuron
cortical postmitotic cell
cortical progenitor cell
D2 receptor expressing neuron
excitatory neuron
hippocampal neuron
inhibitory neuron
layer 6 neuron
neuropeptide Y expressing neuron
nitric oxide synthase expressing neuron

@UlrikeS91 @lzehl Related to openMetadataInitiative/openMINDS_controlledTerms#149, let me know what naming convention you would like to use and I can prepare a PR.

**Comment by lzehl** [comment]
@MaaikevS thanks for preparing this. There are a few that I would not register, because they are semantic combinations with brain regions and not represent necessarily their own class (but feel free to disagree, and discuss). I think we should avoid these where possible (which we did not in the past). @tgbugs your insight here? 

Here the once I would not register:
+ cortical neuron
+ cortical postmitotic cell (I would only register postmitotic cell)
+ cortical progenitor cell (I would only register progenitor cell)
+ hippocampal neuron
+ layer 6 neuron

For the rest: my impression is that the x expressing neurons are typically written as "x-expressing neuron", if the x is one word. Not sure if that is true. The decision of going with ... neuron now instead of ... cell is good I think.

All of those decisions we make now would require us to clean up what we already have in for cell types (in particular the combination of brain region with a general cell type). I think it would be worth it. 

@MaaikevS @UlrikeS91 @tgbugs what do you think?

**Comment by MaaikevS** [comment]
Cell types that are now registered (and cleaned up in the KGE):

aromatase expressing neuron
calbindin expressing neuron
calretinin expressing neuron
choline acetyltransferase expressing neuron
postmitotic cell
progenitor cell
D2 receptor expressing neuron
excitatory neuron
inhibitory neuron
neuropeptide Y expressing neuron
nitric oxide synthase expressing neuron

Further discussion is needed to sort out cell types that refer to an anatomical region

**Comment by lzehl** [comment]
this will be solved with https://github.com/HumanBrainProject/openMINDS_controlledTerms/issues/257
