### ISSUE TITLE
New terminolgy - ExperimentalMeasurement

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#151]
@lzehl @UlrikeS91 Following the ontology meeting, we consider adding a new terminology "experimental measurement".

Suggested terms for this terminology would be the following (not an exhaustive list):
- action potential
- alpha activity
- beta activity
- gamma activity
- inhibitory postsynaptic potential
- inhibitory postsynaptic current
- excitatory postsynaptic potential
- excitatory postsynaptic current
- local field potential
- miniature inhibitory postsynaptic current
- multi-unit activity
- single-unit activity
- slow oscillation
- spike time dependent plasticity
- spontaneous inhibitory postsynaptic current

@apdavison Would this fit your needs for the ephys extension as well?

**Comment by apdavison** [comment]
We already have "measured quantity", which mostly contains terms at the sub-cellular level at the moment (https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances/measuredQuantity), but I think more macroscopic quantities like some of those in the list above would also fit (all of the "potential"s, "current"s, "activity"s).

However, some of the terms in the list, e.g. spike time dependent plasticity, are not measured quantities, but more "studied phenomena".

**Comment by MaaikevS** [comment]
As far as I understand, this is actually to replace the "measured quantity" that is currently there now (please confirm @lzehl ). The reason for this is that some of these quantities are measured and some are calculated, according to Tom. Hence, this might need to be merged. We wanted to discuss this on GitHub to align the different properties.

**Comment by lzehl** [comment]
@apdavison the idea was indeed to merge the macroscopic quantities into the "measured quantity" list and rename this terminology to  "experimental measurement" which fits better with the ontological interpretation of the joint terms.

Could you elaborate which terms exactly besides "spike time dependent plasticity" you would consider rather as "phenomena" and why? 

My problem with "phenomena" vs "measured quantity" is that most phenomena are measured (directly or indirectly) and then what is measured is called the same as the phenomena (or the other way around). For example all potentials are measured biological phenomena (e.g. membrane potential). 

The idea with "experimental measurement" to loosen the context a bit and join all terms that can be/are typically measured in experiments and could also be potential study targets (e.g., also "temperature", "BOLD signal", "peak latency", "long-term potentiation", "long-term depression", "light intensity", etc.)

Here a joint list of the term in "measured quantity" and the new terms with my assessment which of them could also classify as biological phenomena:
- chloride reversal potential (biological phenomena)
- compensation current
- input resistance
- liquid junction potential (biological phenomena)
- measured holding potential (why not just holding potential?)
- membrane potential (biological phenomena)
- seal resistance
- series resistance
- action potential (biological phenomena)
- alpha activity (biological phenomena)
- beta activity (biological phenomena)
- gamma activity (biological phenomena)
- inhibitory postsynaptic potential (biological phenomena)
- inhibitory postsynaptic current (biological phenomena)
- excitatory postsynaptic potential (biological phenomena)
- excitatory postsynaptic current (biological phenomena)
- local field potential (biological phenomena)
- miniature inhibitory postsynaptic current (biological phenomena)
- multi-unit activity (biological phenomena)
- single-unit activity (biological phenomena)
- slow oscillation (biological phenomena)
- spike time dependent plasticity (biological phenomena)
- spontaneous inhibitory postsynaptic current (biological phenomena)

@apdavison what do you think about our approach? do you have any better idea of how to handle this without introducing too many terminologies which are difficult to maintain regarding the decision of what term should go where? (I would also like to avoid repetition of terms in different terminologies)

**Comment by apdavison** [comment]
Could you explain what is motivating this proposal? (i.e. what is the use case, how would this information be used in the KG and the UI).

It seems it is less closely related to "measured quantity" than I initially thought.

For ephys it is important that we can check that the units provided are consistent with what is being measured, so the physical dimensions of what is being measured are required, e.g.:

- chloride reversal potential: voltage (e.g. mV)
- input resistance: electrical resistance (e.g. Mohm)
- beta activity: unclear, could be frequency, or power at a given frequency
- single-unit activity: time^-1 (e.g. spikes/second)
- slow oscillation: frequency (e.g. Hz) - but "slow" is irrelevant in this use case, it would be "oscillation frequency"
- spike time dependent plasticity: completely unclear, there are many different attributes of STDP you could measure.

Probably we are looking at two schemas, with not much repetition/overlap. I don't think "experimental measurement" is a good name for the new schema given the range of terms you propose to include. "biological phenomenon", or "neuroscience concept" seem like better fits.

p.s. "(why not just holding potential?)" - because we also have "target holding potential", which is a parameter rather than a measurement.

**Comment by lzehl** [comment]
@apdavison motivation is that we want to cover as many terms in the openMINDS libraries of controlled terms as possible. Currently there are many undefined term suggestions around "biological phenomenons" or "neuronal signals". The list above is an extraction of those undefined terms.

The "terminology" divisions of controlled terms into terminology schemas was mainly done to be able to target a subset of controlled terms as linked types for certain properties. For this reason the openMINDS terminologies do not follow necessarily the ontological super-classes which are more fine-grained and not necessarily intuitive for the typical community. Also we don't want openMINDS to rebuild the relations between terms, but want to leave this to the ontology.

I'm happy about any suggestions for the terms discussed above. It could be one or two terminologies. 

General guidelines for terminologies: 
+ Terms should be registered once, meaning in one terminology, not multiple ones (avoiding duplicates also across terminologies).
+ Adding new terms to the terminologies should be easy meaning avoiding classifications which are not intuitive to extend (avoiding the repeating question: should new term go to terminology A or B?). 
+ Terms of one terminologies should be potentially meaningful in context of one property. A property could expect terms from one or multiple terminologies (e.g., subject/ageCategory -> AgeCategory terms, datasetVersion/studyTarget -> all Terminologies of category studyTarget, etc.) .

**Comment by lzehl** [comment]
@apdavison did we come to a solution for this issue? if not do we need to have a meeting to discuss in person?

**Comment by lzehl** [comment]
@apdavison @UlrikeS91 : @MaaikevS @tgbugs and I discussed this one again. here our result :

We keep all "single-value" stuff that can be directly or indirectly measured (e.g. membrane potential, chloride reversal potential, input resistence) in MeasuredQuantity. @apdavison here it would be good though to replace "measuredHoldingPotential" with just "holdingPotential" and move the "measured" vs "target"(?) to the property name (and/or instruction) of the schema where you use it.

All more complex things (e.g. local field potential, alpha oscillation, single-unit activity, etc) we keep under BiologicalProcess (this would be a new terminology grouping).

Both terminologies ( MeasuredQuantity and BiologicalProcess ) should be added to the potential study target list (and later also be an option for keywords ).

We hope this is a good solution which satisfies all our needs. Do you agree?

**Comment by UlrikeS91** [comment]
Sounds good to me, but I also don't have a strong opinion about this anyway.

**Comment by apdavison** [comment]
@lzehl sounds fine to me. I've fixed the "holding potential" issue in #230

**Comment by lzehl** [comment]
@apdavison and @UlrikeS91 perfect! The PR [#230](https://github.com/HumanBrainProject/openMINDS_controlledTerms/pull/230) is already merged. 

@MaaikevS do you want to take over the PR for the BiologicalProcess schema + instances (initial selection)? Please let me know if you don't have the time at the moment.

**Comment by UlrikeS91** [comment]
If I interpret this correctly, the only open issue here is the biological process, right? I made an issue for this specifically and close this issue for now. @lzehl feel free to reopen it, if my interpretation was wrong 🙂

**Comment by ehennestad** [comment]
The earlier discussion in this issue refers to many of these concepts as biological phenomenon, whereas the conclusion is to make a new schema called `BiologicalProcess`. I think `BiologicalPhenomenon` is much better because none of the concepts listed in the first post fit well with the definition of a process. A process is generally understood as " a series of actions or operations conducing to an end" (merriam webster).

On the other hand, a phenomenon is defined as "an observable fact or event". I agree that this is similar to a measured quantity but I think it has some notable differences. Let's take an action potential as an example. What is measured is the membrane potential whereas the action potential is an observable event that happens in a short time window. It is also not a process, because it does not lead to anything. The propagation of the action potential on the other hand might be considered a process...?

When it comes to oscillations, they are definitely not processes (its not even clear what the biological fingerprint is or if it has biological relevance), they are quantities that are derived from measurements. You don't measure the oscillations, you measure the extracellular potential or the EEG and you compute the power of the signal within frequency bands. They are observable and they are often also observed with time intervals (events) so they can also fall in under the phenomena definition. 

For some of the others e.g inhibitory postsynaptic potential, inhibitory postsynaptic current, excitatory postsynaptic potential, excitatory postsynaptic current, they are measured quantities (membrane potentials), but at specific locations... I therefore do not think it is right to classify them as phenomena, since they are more directly related to actual measurements (also they are not considered events).

**Comment by ehennestad** [comment]
On second thought, IPSP/EPSP/IPSC/EPSC are similar to action potentials, so they should not be considered measured quantities...

**Comment by lzehl** [comment]
@ehennestad you are fully right. We agreed in 'measured quantities' we only keep single valued elements (e.g., membrane potential). Everything more complex should be registered as BiologicalProcess. We can also name this terminology BiologicalPhenomenon @UlrikeS91 & @tgbugs any objections?

**Comment by UlrikeS91** [comment]
I like BiologicalPhenomenon better. Based on the terms that I found for the terminology, it would make more sense.
