### ISSUE TITLE
UBERONparcellation: V4

### ISSUE THREAD

**Issue by ingrre** [HumanBrainProject/openMINDS_controlledTerms#166]
Hi! I want to add V1 and V4 to a macaque dataset (this one specifically: https://www.nature.com/articles/s41597-022-01180-1#citeas). I can use UBERONparcellations, but only primary visual cortex exists, so I would like to ask you to add V4. I could however not immediately find it in the ontology search (https://www.ebi.ac.uk/ols/ontologies/uberon). Hope you can help me find a viable solution.

**Comment by lzehl** [comment]
@ingrre V4 is not registered in UBERON (yet). Did you ask the data provider if they typically use a specific macaque atlas/parcellation?

For EBRAINS curation: Feel free to add areas you cannot find anywhere as Custom Anatomical Entity. Note: For macaques we should move to using the areas of the MEBRAINS atlas if the data provider does not state he/she used an other specific macaque atlas. Note that the MEBRAINS areas are not yet registered in SANDS but for EBRAINS you can find them some of them already registered as Custom Anatomical Entity (Area V4 would be actually two V4v + V4d in MEBRAINS).

**Comment by UlrikeS91** [comment]
This was solved by the use of custom anatomical entities. We considered using UBERON parcellations but it turns out that V4 does not exist or at least I couldn't find it. The closest match was "visual association cortex" (which includes more than just V4), "extrastriate cortex" (which includes V2, V3, V4 and V5) or "Brodmann area 19" (which still includes V2, V4 and V5, and also has a "human" ring to it). 

This is just to show how the issue was solved and to note that V4 does not exist stand-alone in UBERON. I will close this issue now since there is nothing more to do in relation to it as far as I can tell.
