### ISSUE TITLE
subject state attribution - 2 new suggestions

### ISSUE THREAD

**Issue by AnnaHilverling** [HumanBrainProject/openMINDS_controlledTerms#173]
Hi all, I would like to suggest two new attributes in subjectState: 
1. congenitally blind
2. acquired blind

For now I have added 'congenitally blind individuals' under additional remarks in the subjectState. Or do you think this solutions is appropriate?

**Comment by lzehl** [comment]
@AnnaHilverling thanks for raising the issue. 
@UlrikeS91 & @MaaikevS I think those terms might be better suited in our Disease terminology ?

**Comment by MaaikevS** [comment]
@lzehl I agree. They are better suited in the Disease terminology

**Comment by UlrikeS91** [comment]
Yes, I would argue that both are pathologies of the individuals and "congenitally blind" certainly falls under the "disease" category in openMINDS.

I would add "congenital blindness" as a controlledTerms/disease with the following definition:
_Congenitally blind individuals were born with permanent and irreversible lack of or severely impaired vision._

The description could elaborate:
_Congenital blindness refers to a group of diseases and conditions occurring in childhood or early adolescence. It can be caused by an underlying disease (e.g., optic nerve hypoplasia) or complications during pregnancy or birth (e.g., hypoxia, an infection during pregnancy, premature birth), and typically results in severe visual impairments or blindness. If left untreated, congenitally blind individuals are likely to be permanently blind later in life._ 

As far as I can see  "acquired blind" refers to individuals have lost their vision later in their life but could see as e.g. children/adolescent. This would be my suggestion for the controlledTerms/disease instance: 
"acquired blindness" 
definition: _A condition in which individuals had little to no impairments in their eye sight (and development of their vision) but have become blind at a later stage in their life (e.g., during adulthood)._
description: _Acquired blindness refers to a group of diseases and conditions typically occurring in adulthood where an individual had normal eye sight but lost it later on. Causes are widespread. Individuals could have lost their eye sight because of head trauma, other accidents or diseases (e.g. retinitis pigmentosa, (childhood) meningitis, glaucoma)._ 

@AnnaHilverling, would this work for you?

**Comment by AnnaHilverling** [comment]
Hi all, thanks so much for all your input.

@UlrikeS91 Thanks for working out the descriptions and definitions. 

But I don't know exactly if I can agree that congenital blindness or acquired blindness is entered as a disease. I would rather say that it is a resulting condition from a disease and should not be defined as a disease itself. 
What do you think?

As already stated in the definitions above it is a "condition", and as stated in the descriptions above these conditions "refer to a group of diseases" (from which this condition arises as a result).

**Comment by MaaikevS** [comment]
Following the definitions I found online, I would argue blindness might be best described as a disorder.

A **disease** is a pathophysiological response to internal or external factors.
A **disorder** is a disruption to regular bodily structure and function.
A **syndrome** is a collection of signs and symptoms associated with a specific health-related cause.
A **condition** is an abnormal state of health that interferes with normal or regular feelings of wellbeing.

The question is whether we are categorising all the above in one single category "disease" or that we want to give some nuance to them.

**Comment by UlrikeS91** [comment]
I understand the confusion, and semantically agree with both @AnnaHilverling and @MaaikevS that blindness is not a disease. Our original idea was to basically collect every abnormal pathology/deviation from normal pathology in "disease". 

@AnnaHilverling ignore the name "disease" now - Would you agree that blindness is a pathological change in the body (e.g., [definition of "pathologcial"](https://www.merriam-webster.com/dictionary/pathological): altered or caused by disease)?

If yes, then you would have to register it under "pathology" for the specimen (choosing from controlledTerms/disease or controlledTerms/diseaseModel).

**Comment by AnnaHilverling** [comment]
Hi @MaaikevS and @UlrikeS91, many thanks for your reponse. 

@UlrikeS91 I understand your original idea. So, yes, I agree that blindness is a pathological change in the body caused by a disease.

**Comment by lzehl** [comment]
@MaaikevS this is a good suggestion to refine the "disease" terms into better fitting terminologies. I would stick for now to disease and disorder, since syndrome and condition are "properties" of diseases and disorders.

@UlrikeS91 do we have only diseases now in "disease" or is there already a mix between disease and disorder?
