### ISSUE TITLE
subjectAttribute: counter attribute to "hasImplanted/InsertedDevice" ? 

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#245]
@tgbugs : what do you think? is this "control" or should there be an additional attribute (as for e.g. "treated" vs "untreated")

**Comment by lzehl** [comment]
additionally: what about attached devices? (e.g. EEG caps)

**Comment by tgbugs** [comment]
We called this experimental group, but the issue here is whether this is before and after some procedure, how do we deal with such internal control cases where we need to be able to distinguish the states based on critical variables.

Another case would be simulated and unstimulated or with stimulus presentation and without. This can get into super detailed task structure. Unimplanted vs implanted vs sham. Also could have an internal control case where there are two sites, one with implantation and one with sham.

Another case would be varying dose.

An additional wrinkle is that many times these are paired or grouped into mutually exclusive states, such as asleep, awake, anaesthetized, comatose.

Another possibility might be to provide sequencing information for subject states, but ideally that would be templated not per subject.

We were dealing with this for implanted sensors. This is similar to the image/roi, subject/sample, and now subject/site.

The maximalish solution is to create explicit attribute sets of N attrs that appear in M unique states. That way e.g. `{pre-treatment/pre-placebo post-treatment post-placebo} (3 2)`  would be able to automatically validate that all subjects have two states. This doesn't quite provide the additional constraint that there must be a pre/post pair, you could accidentlly get post/post. `{pre {post-1 post-2}}` a bit closer.

Because you can have multiple attributes you can create intra-subject pairs, within subject `{pre post}` and then within post you could have a cross subject pair `{placebo treatment}`.

**Comment by lzehl** [comment]
https://github.com/HumanBrainProject/openMINDS_controlledTerms/tree/v1/instances/subjectAttribute

**Comment by lzehl** [comment]
anaesthetized vs awake
asleep vs awake
comatose vs ?? ALERT
deceased vs ALIVE (missing)
freelyMoving vs restrained
freelyMoving vs headRestrained
knockin vs control
knockout vs control
treated vs untreated
drugged vs untreated (merge drugged into treated ?)
hasImplantedDevice vs PREOPERATION | POSTOPERATION
hasInsertedDevice vs PREOPERATION | POSTOPERATION
hasAttachedDevice (missing) vs ??

**Comment by lzehl** [comment]
PLACEBO (missing) vs treated

**Comment by lzehl** [comment]
trained vs untrained

**Comment by UlrikeS91** [comment]
This is missing some clues for me to participate in the discussion. We can either discuss this during one of our meetings or somebody needs to fill in some gaps here😉

**Comment by lzehl** [comment]
@UlrikeS91 discussion is done. We just need to add some of the missing terms (that list probably will grow, but these were the ones we identified for now):
"alive"
"alert"
"preoperative"
"postoperative"
"placebo"
