### ISSUE TITLE
new technique: blood sample extraction ???

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#273]
@tgbugs and @UlrikeS91 I need your feedback here ;)

**Comment by UlrikeS91** [comment]
The term in itself is weird, because I would call this "blood sample taking" or "blood sampling". Extraction in this context is a bit weird. I would like to have such extraction techniques as controlled terms - also e.g. "brain extraction". We could generalize it to "specimen extraction" and/or "specimen sampling".

**Comment by lzehl** [comment]
@UlrikeS91 I researched a bit and although blood is an organ and we could run its extraction under "organ extraction" I think it makes sense here to introduce a specific term. Apparently it is typically called "blood sampling". I'll make a respective PR if you agree
