### ISSUE TITLE
New technique suggestion: Spectral Segmentation

### ISSUE THREAD

**Issue by archgogo** [HumanBrainProject/openMINDS_controlledTerms#309]
Hi,

Could you add "Spectral Segmentation" as a technique?
Here is the link with more info
https://github.com/Leveltlab/SpectralSegmentation

**Comment by UlrikeS91** [comment]
Thanks for raising the issue. @lzehl what do you think? We have "anatomical segmentation technique". To me it sounds correct to add "spectral segmentation technique" as well. What do you think?

**Comment by lzehl** [comment]
@UlrikeS91 theoretically this is can be considered a subtype of an anatomical segmentation technique (since they use it to define masks for neuron cell bodies). Nonetheless it could be used for non-anatomical segmentation problems as well therefore we should discuss it as a separate segmentation technique term.

For registration I would probably call this "cross-spectral power-based image segmentation" OR "spectral power image segmentation". (not sure if we need "image" in the term)

@tgbugs : I'd like your opinion here from the ontology perspective.

**Comment by lzehl** [comment]
@tgbugs and @ehennestad suggest to add also the super class for this technique which would be "auto-segmentation"

**Comment by tgbugs** [comment]
With auto-segmentation this becomes a subclass of auto-segmentation that uses a power spectrum over the time series for individual pixels or voxels in the image to generate the segmentation.

**Comment by lzehl** [comment]
so we suggest to register as well "spectral power auto-segmentation"

**Comment by lzehl** [comment]
@chrisvdt what is your opinion here? could you give us inside as develper of the tool https://github.com/Leveltlab/SpectralSegmentation ?

**Comment by chrisvdt** [comment]
Interesting discussion.  @tgbugs comment describes the software correctly. Spectral power based auto-segmentation would be a correct term. The technique is only for image segmentation in image sequences (movies), not for static images or other type of data, because it depends on functional changes in pixel fluorescence traces.
hope this clarifies things.

**Comment by tgbugs** [comment]
closed via https://github.com/HumanBrainProject/openMINDS_controlledTerms/pull/373
