### ISSUE TITLE
Request for Reference field in Protocol

### ISSUE THREAD

**Issue by maciej-jedynak** [HumanBrainProject/openMINDS_controlledTerms#363]
While describing a new protocol, it could be useful to have a structure for references (in the sense of bibliography).

**Comment by lzehl** [comment]
@maciej-jedynak thank you for this issue. But could you specify this more (here I would suggest to make use of markdown hyperlinks in the protocol description for the paper you reference)? Or do you want to have a list of references or explicitly highlight one reference where the protocol was first described (the "described in" property should already be there)?

Note: this issue is affecting the Protocol Schema which is part of the openMINDS_core Repository. If this issue will lead to a PR this will happen there not in the openMINDS_controlledTerms Repo.

**Comment by lzehl** [comment]
For the EBRAINS Editor: the property "described in" does not show up yet. It will appear after the next update of the Editor. @maciej-jedynak I'll keep you informed.

**Comment by lzehl** [comment]
solved in https://github.com/HumanBrainProject/openMINDS_core/pull/370
