### ISSUE TITLE
revising software features

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#46]
@bweyers & @jagru20 

I've realized that a number of data types are listed under software features (SoftwareFeature schema + instances). 
For example:
+ 3DGeometryDataTypes
+ 3DVectorDataTypes
+ timeSeriesDataTypes
etc.

Could we separate those as actual data types (DataTypes schema + instances)?
These are not really a feature, correct? But rather the overall class of data types the software can handle/produces?
If this is true, should this be listed as separate property in SoftwareVersion or still under "softwareFeature" as second linked type (SoftwareFeature + DataType)?

**Comment by UlrikeS91** [comment]
> @bweyers & @jagru20
> 
> I've realized that a number of data types are listed under software features (SoftwareFeature schema + instances).
> For example:
> 
> * 3DGeometryDataTypes
> * 3DVectorDataTypes
> * timeSeriesDataTypes
>   etc.
> 
> Could we separate those as actual data types (DataTypes schema + instances)?
> These are not really a feature, correct? But rather the overall class of data types the software can handle/produces?
> If this is true, should this be listed as separate property in SoftwareVersion or still under "softwareFeature" as second linked type (SoftwareFeature + DataType)?

@bweyers and @jagru20 Would you be able to provide some feedback to @lzehl issue? 

(PS: @lzehl, raising issues during vacation time is usually a bad idea 😆🙈)

**Comment by jagru20** [comment]
We have discussed this in a video call and came to the followingː
For now, the data types remain under software feature. Additionally, the contenttype schema gets added an optional property "dataTypes" which can hold one or more of these datatypes. This enables filtering for software or datasets that contain/handle datatypes on a more general level instead of searching for a specific contenttype. 
At a point in time, when the contenttypes are curated in terms of adding all related dataTypes (or at least most of them) the dataTypes in softwareFeature will become obsolete and can be removed.
