### ISSUE TITLE
reassessing / extending TissueSampleType instances

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#55]
list from @tgbugs on sample_types:
1. 'whole organism' (this we don't need, because this is a subject in our case)
2. 'whole organ' (is already in instances)
3. 'fluid specimen' (suggestion: integrate as "body fluid" ? )
4. 'tissue' (not sure what is meant here; we would need somthing like "tissue block"; cf. discussion below)
5. 'nerve' (could be integrated as is)
6. 'slice'  (is already integrated as "tissue slice")
7. 'section'  (see discussion points below)
8. 'cryosection' (I would not integrate this; mixes extraction / fixation procedure with tissue sample type)
9. 'cell' (suggestion: integrate as "single cell" ? )
10. 'nucleus' (I would not integrate this for now)
11. 'nucleic acid'  (I would not integrate this for now)
12. 'slide'  (see discussion points below)
13. 'whole mount' (see discussion points below)
14. 'cell suspension'  (could be integrated as is)
15. 'single cell suspension'  (not sure what the difference is to 'cell')

In openMINDS we registered so far:
1. 'biopsy sample' (cf. the above, I would keep this one)
2. 'brain hemisphere' (I would keep this one or is there a more general term, e.g. 'organ hemisphere' we would prefer?)
3. 'cell culture' (we discussed to replaces this with 'cell line' ?)
4. 'tissue slice' (cf. the above, I would keep this one)
5. 'whole organ' (cf. the above, I would keep this one)

**'slice' vs 'slide' vs 'section' vs 'whole mount' vs 'tissue block'**  
- **'slice'**: a tissue slice is for me just an unprocessed thin slice from a larger sample; does typically require specific sectioning / slicing devices
- **'slide'**:  a tissue slide is for me a tissue slice mounted on a object plate for, e.g., microscopy (can but does not have to be fixated and stained)
- **'section'**: is for me a synonym for slice
- **'whole mount'**: searched for it and mostly found "entire organism or structure which can be studied under microscope without further slicing" [so for me that would mean 'tissue block' is to 'whole mount' what 'slice' is to 'slide']
- **'tissue block'**: a tissue block measures for me a few centimeters or more; does not necessarily require specific devices (but a knife / scalpel)

@UlrikeS91 what do you think?
@tgbugs your thoughts??

**Comment by UlrikeS91** [comment]
Sorry, this slipped through somehow...

Let's see:
> 1. 'whole organism' (this we don't need, because this is a subject in our case)
> 2. 'whole organ' (is already in instances)

agreed
> 3. 'fluid specimen' (suggestion: integrate as "body fluid" ? )

Body fluid is a fluid specimen but not every fluid specimen is body fluid. No objections to adding body fluid, though, just not ok with it if you think they mean the same thing. Maybe we add body fluid and see if this will suffices for now (and if not we can come back to fluid specimen)?
> 4. 'tissue' (not sure what is meant here; we would need somthing like "tissue block"; cf. discussion below)

If I remember correct, we don't need that because this is what our "tissueSample(Collection)" schemas represent. 
> 5. 'nerve' (could be integrated as is)
> 6. 'slice'  (is already integrated as "tissue slice")

agreed
> 7. 'section'  (see discussion points below)

below
> 8. 'cryosection' (I would not integrate this; mixes extraction / fixation procedure with tissue sample type)

agreed, to me this is also more a procedural thing and doesn't fit what we want to capture in the tissueSampleType (but maybe in the new "tissueSampleAttribute" somehow?)
> 9. 'cell' (suggestion: integrate as "single cell" ? )

agreed, but should there also be a term for multiple cells? 
> 10. 'nucleus' (I would not integrate this for now)
> 11. 'nucleic acid'  (I would not integrate this for now)

fine by me
> 12. 'slide'  (see discussion points below)
> 13. 'whole mount' (see discussion points below)

below
> 14. 'cell suspension'  (could be integrated as is)
> 15. 'single cell suspension'  (not sure what the difference is to 'cell')

The suspension part is the difference, so a fluid containing a single cell. But cells don't all have to be in suspension😉
Would 'cell suspension' then represent a fluid containing more than a single cell? 



> In openMINDS we registered so far:
> 
> 1. 'biopsy sample' (cf. the above, I would keep this one)
> 2. 'brain hemisphere' (I would keep this one or is there a more general term, e.g. 'organ hemisphere' we would prefer?)
> 3. 'cell culture' (we discussed to replaces this with 'cell line' ?)

Don't remember the outcome, but remember that 'cell culture' wasn't ideal. @tgbugs, can you explain why again? 

> 4. 'tissue slice' (cf. the above, I would keep this one)
> 5. 'whole organ' (cf. the above, I would keep this one)

1-2 & 4-5 agreed


> **'slice' vs 'slide' vs 'section' vs 'whole mount' vs 'tissue block'**
> 
> * **'slice'**: a tissue slice is for me just an unprocessed thin slice from a larger sample; does typically require specific sectioning / slicing devices
> * **'slide'**:  a tissue slide is for me a tissue slice mounted on a object plate for, e.g., microscopy (can but does not have to be fixated and stained)
> * **'section'**: is for me a synonym for slice

I think I said that during the meeting about this: To me, they are all the same 😅 I understand that they are not, but I don't believe we need more then 'slice'. I think your definition for 'slide' is also what @tgbugs said, but this would include procedural aspects again (similar to 'cryosection', see above) which we don't want to capture in our "tissueSampleType".  
 
> * **'whole mount'**: searched for it and mostly found "entire organism or structure which can be studied under microscope without further slicing" [so for me that would mean 'tissue block' is to 'whole mount' what 'slice' is to 'slide']
> * **'tissue block'**: a tissue block measures for me a few centimeters or more; does not necessarily require specific devices (but a knife / scalpel)

I don't know. There is this procedural aspect again if @lzehl comparison with 'slide' and 'slice' is true...So, you would argue that 'tissueBlock' is what we should add?

**Comment by lzehl** [comment]
What we need to do:

    'biopsy sample' (keep, no action)
    'brain hemisphere' (rename to 'organ hemisphere'?)
    'cell culture' (rename to 'cell line' ?)
    'tissue slice' (keep, no action)
    'whole organ' (keep, no action)
    'fluid specimen' (add)
    'single cell' (add)
    'cell population' (add ? does this collide with 'cell line'?)
    'tissue block' (add)

I wonder if we leave out the others because that can be covered in attribute and protocol executions.
@UlrikeS91 what do you think?

**Comment by UlrikeS91** [comment]
@lzehl suggestion | my comment 
-------------------- | ----------------
'biopsy sample' (keep, no action) | yes
'brain hemisphere' (rename to 'organ hemisphere'?) | yes, rename; just to make sure: a part of an organ (less than a hemisphere/part from an organ that is not bilateral) would fall under "biopsy sample", right?
'cell culture' (rename to 'cell line' ?) | yes, culture was bad for some reason (maybe because it includes some procedural steps); cell line should work 
'tissue slice' (keep, no action) | yes
'whole organ' (keep, no action) | yes
'fluid specimen' (add) | yes
'single cell' (add) | yes
'cell population' (add ? does this collide with 'cell line'?) | depends on the definitions of the two, but if I'm not mistaken a "cell line" can only be of one type of cell; cell population could include a population of different cells then? Or? 
'tissue block' (add) | yes
. | `nerve` was mentioned above as "could be integrated as is"; did you forget it or deliberately excluded it?
. | `cell suspenison`  was mentioned above as "could be integrated as is"; did you forget it or deliberately excluded it?

**Comment by lzehl** [comment]
for "hemisphere" only works for bilateral organs; parts of not bilateral organs could be "biobsy sample" or "tissue block"

for "cell population" vs "cell line": exactly a cell line is a population of a specific cell type, while a cell population could be also consist of various cell types... I wonder if we should name the terms: "cell population - defined" (for cell lines) and "cell population - undefined" for all others.

"cell suspension" I deliberately left out because this is for me covered in "cell population" / "cell line" and "single cell". That these are in a suspension is for me an attribute we could add. 

"nerve" I simply forgot...

**Comment by UlrikeS91** [comment]
> for "hemisphere" only works for bilateral organs; parts of not bilateral organs could be "biobsy sample" or "tissue block"

Yes, that's what I thought/hoped would be the answer ☺️ 


> for "cell population" vs "cell line": exactly a cell line is a population of a specific cell type, while a cell population could be also consist of various cell types... I wonder if we should name the terms: "cell population - defined" (for cell lines) and "cell population - undefined" for all others.

I like the direction of this suggestion but not the terms...How about: 
1. "cell population of one (cell) type" & "cell population of several (cell) types"
2. "homogeneous cell population" & "heterogeneous cell population"
(PS: Don't like either of these suggestions 100% but maybe they spark an idea 😉) 

> "cell suspension" I deliberately left out because this is for me covered in "cell population" / "cell line" and "single cell". That these are in a suspension is for me an attribute we could add.

Okay. That sounds like a good plan to me.

> "nerve" I simply forgot...

Happens 😉

**Comment by lzehl** [comment]
actually I like "homogeneous cell population" & "heterogeneous cell population" a lot
do we have an agreement then?  @UlrikeS91 and @tgbugs

**Comment by lzehl** [comment]
question: do we need to name it "organHemisphere" or could we just use "hemisphere"? @UlrikeS91 and @tgbugs

**Comment by lzehl** [comment]
SUMMARY for TissueSampleType we want to have: 
        'whole organ'
        'hemisphere'
        'tissue block'
        'tissue slice'
        'biopsy sample' 
        'fluid specimen'
        'homogeneous cell population'
        'heterogeneous cell population'
        'single cell'

**Comment by lzehl** [comment]
@apdavison is this fitting with your needs?

**Comment by UlrikeS91** [comment]
> SUMMARY for TissueSampleType we want to have: 
'whole organ' 
'hemisphere' 
'tissue block'
'tissue slice' 
'biopsy sample' 
'fluid specimen' 
'homogeneous cell population' 
'heterogeneous cell population' 
'single cell'

You forgot `nerve` again 😆 

"homogeneous cell population"/"heterogeneous cell population" just sounded a bit off in my head, but if you like it and it expresses what we need, I'm fine with adding them (with good definitions, though) ☺️

**Comment by lzehl** [comment]
these nerves... :joy:

**Comment by lzehl** [comment]
@UlrikeS91 can you prepare the PR or should I do it?

**Comment by UlrikeS91** [comment]
> @UlrikeS91 can you prepare the PR or should I do it?

I can do it tomorrow 🙂

**Comment by lzehl** [comment]
@UlrikeS91 thank you :pray:
