### ISSUE TITLE
Suggestions 

### ISSUE THREAD

**Issue by MaaikevS** [HumanBrainProject/openMINDS_controlledTerms#62]
Hi! 

Based on the datasets that I have been working with, I would like to suggest that the following few things may need to be added. If they are already covered by an existing term, please let me know.

1. electroporation as technique
2. stereology as experimental approach
3. volume fraction estimation as technique (or I need to add a different technique and put this in a protocol/execution)
4. intracellular electrophysiology as technique
5. high-frequency electrical stimulation as technique (currently only single pulse electrical stimulation is available)

**Comment by UlrikeS91** [comment]
discussed in an offline meeting with @tgbugs & @lzehl: 

1. electroporation will be added as a technique (interlex: https://scicrunch.org/scicrunch/interlex/view/ilx_0739748)
2. "cell population characterization" covers a little portion of it, but will be added as a technique (interlex: https://scicrunch.org/scicrunch/interlex/view/ilx_0739729)
3. if related to this dataset: https://search.kg.ebrains.eu/instances/ae523e54-b46a-4e01-8365-0db9d420cc1a, stereology is the technique and volume fraction estimation would be more suitable as a study target (or worst case as a keyword) 
4. a) intracellular electrophysiology will be added as technique (interlex: https://scicrunch.org/scicrunch/interlex/view/ilx_0739521)
4. b) we will also add sharp intracellular electrode technique (interlex: https://scicrunch.org/scicrunch/interlex/view/ilx_0739713)
5. high-frequency electrical stimulation won't be added, and single pulse electrical stimulation will be removed/renamed to just "electrical stimulation" (because single pulse and/or high-frequency describe detailed parameters and are too specific) (interlex: https://scicrunch.org/scicrunch/interlex/view/ilx_0739699)

I'll prepare the PR tomorrow morning.

**Comment by MaaikevS** [comment]
Thank you!
