### ISSUE TITLE
adding molecularEntity

### ISSUE THREAD

**Issue by lzehl** [HumanBrainProject/openMINDS_controlledTerms#83]
@tgbugs & @UlrikeS91 I'm surprised that no one requested that yet... we postponed this for a while.
do you agree adding the schema and at least some instances?

[@UlrikeS91 did you prepare something for this already? I have the feeling you did... if so, feel free to forward, I can take over if you want]

**Comment by UlrikeS91** [comment]
Yes, I have some first instances for a molecularEntity terminology ☺️ I have a list that includes more than just those, so it's not smart to link it here. But we can discuss the list offline and I can make a PR with what we landed on/want to include (which can be up for feedback from the broader community afterwards instead). 

Sounds good?

**Comment by tgbugs** [comment]
I'm guessing the domain is CHEBI + protein ontology/uniprot, so small molecules and proteins? Would this also cover engineered proteins such as eGFP, RFP, etc. which might have certain metadata templates about excitation frequencies or similar?

**Comment by UlrikeS91** [comment]
@tgbugs, here is an excerpt from the list. "Keywords from EBRAINS KG" are terms that have been stated as keywords in KG v2, then I did a rough "categorization" stating a potential terminology the term could fit in (here you only got the terms that could have something to do with molecular entities), "openMINDS (potential) name" states the (re)curate name of the term (work in progress, which is why several of them are still empty), "InterLex" states the InterLex IRI (if I could find one) and "preferred ontology ID" states either the IRI that has been stated as preferred in InterLex or, if I couldn't find it in InterLex, another ontology. 
When a term wasn't included in InterLex, my first "go-to" was CHEBI. In some cases, I also used the CHEBI as preferred ID even though InterLex stated something else as preferred (e.g. for chemical agents like isoflurane or DAB). A few also point to the protein ontology (e.g. Neuroligin 3) but I think those are mostly cases where the protein ontology was listed in InterLex.

eGFP, RFP and such haven't been used as keywords in the KG. Closest to those are probably terms like "Alexa Fluor 594" or "FluorRuby", which I would include in the molecularEntity terminology for openMINDS. So, I would probably add terms like eGF/RFP/etc. as well. 
The original idea for this terminology was to not restrict it too much and collect anything that loosely related to it, and rather later on split it up into several sub-terminologies (with stricter definitions). 


keyword from EBRAINS KG | categorization | openMINDS (potential) name | InterLex | preferred ontology ID
-- | -- | -- | -- | --
ABetaX-40 | MolecularEntity | Beta-Amyloid 40 | http://uri.interlex.org/ilx_0101246 | http://uri.neuinfo.org/nif/nifstd/nlx_13181
adenosine receptor A1 | MolecularEntity | adenosine A1 receptor | http://uri.interlex.org/ilx_0100146 | http://uri.neuinfo.org/nif/nifstd/nifext_5717
adenosine receptor A2A | MolecularEntity | adenosine A2A receptor | http://uri.interlex.org/ilx_0100148 | http://uri.neuinfo.org/nif/nifstd/nifext_7727
Alexa Fluor 594 | MolecularEntity | Alexa Fluor 594 | null | http://purl.obolibrary.org/obo/CHEBI_51248
Anterograde Tracer | MolecularEntity | anterograde tracer | null | http://purl.obolibrary.org/obo/NLXMOL_1012002
anterograde tracer | MolecularEntity | anterograde tracer | null | http://purl.obolibrary.org/obo/NLXMOL_1012002
BDA | MolecularEntity | biotinylated dextran amine | http://uri.interlex.org/ilx_0450726 | http://id.nlm.nih.gov/mesh/2018/M0205506
biomarkers | MolecularEntity | biomarker | http://uri.interlex.org/ilx_0101294 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090517
Biotinylated dextran amine | MolecularEntity | biotinylated dextran amine | http://uri.interlex.org/ilx_0450726 | http://id.nlm.nih.gov/mesh/2018/M0205506
C-fos | MolecularEntity | c-FOS | null | null
Ca2+/calmodulin-dependent protein kinase II promoter | MolecularEntity | calcium calmodulin protein kinase II promoter | null | null
  | MolecularEntity | calcium calmodulin protein kinase II | http://uri.interlex.org/ilx_0101561 | http://purl.obolibrary.org/obo/PR_000003197
Calbindin | MolecularEntity | calbindin | http://uri.interlex.org/ilx_0101551 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_1006006
Calretinin | MolecularEntity | calretinin | http://uri.interlex.org/ilx_0101602 | http://uri.neuinfo.org/nif/nifstd/nifext_5717
Camk2a | MolecularEntity | calcium calmodulin protein kinase II alpha chain | null | http://purl.obolibrary.org/obo/PR_000003199
Chemical markers | MolecularEntity | chemical marker | null | null
cyclic AMP | MolecularEntity | cyclic adenosine monophosphate | http://uri.interlex.org/ilx_0100318 | http://purl.obolibrary.org/obo/CHEBI_17489
DAB | MolecularEntity | DAB | http://uri.interlex.org/ilx_0482636 | http://purl.obolibrary.org/obo/CHEBI_90994
Dopamine D1 receptor | MolecularEntity | D1 dopamine receptor | http://uri.interlex.org/ilx_0102774 | http://uri.neuinfo.org/nif/nifstd/nifext_5845
Dopamine D2 receptor | MolecularEntity | D2 dopamine receptor | http://uri.interlex.org/ilx_0102775 | http://uri.neuinfo.org/nif/nifstd/nifext_5833
Fluorescent microspheres | MolecularEntity | fluorescent microspheres | null | null
Fluoro-gold | MolecularEntity | Fluoro-Gold | http://uri.interlex.org/ilx_0104323 | http://uri.neuinfo.org/nif/nifstd/nlx_30125
FluoroEmerald | MolecularEntity | Fluoro-Emerald | null | null
FluoroRuby | MolecularEntity | Fluoro-Ruby | http://uri.interlex.org/ilx_0104322 | http://uri.neuinfo.org/nif/nifstd/nlx_65982
GABA receptor | MolecularEntity | GABA receptor | http://uri.interlex.org/ilx_0104502 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_1006001
GABAA receptor | MolecularEntity | GABA-A receptor | null | null
GABAB receptor | MolecularEntity | GABA-B receptor | http://uri.interlex.org/ilx_0104503 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_090801
GLT1 | MolecularEntity | glutamate transporter 1 | null | null
Glutamate transporter | MolecularEntity | glutamate transporter | http://uri.interlex.org/ilx_0104678 | http://uri.neuinfo.org/nif/nifstd/sao1399894198
Glycine transporter type 2 | MolecularEntity | glycine transporter 2 | null | null
Growth factor | MolecularEntity | growth factor | http://uri.interlex.org/ilx_0104801 | http://uri.neuinfo.org/nif/nifstd/sao1671627152
Intrabodies | MolecularEntity | intrabody | null | null
  | MolecularEntity | ionotropic glutamate receptor | http://uri.interlex.org/ilx_0105706 | http://uri.neuinfo.org/nif/nifstd/nlx_mol_20090501
ionotropic glutamate AMPA receptor | MolecularEntity | AMPA receptor | http://uri.interlex.org/ilx_0100559 | http://uri.neuinfo.org/nif/nifstd/nifext_5251
ionotropic glutamate kainate receptor | MolecularEntity | kainate receptor | http://uri.interlex.org/ilx_0105822 | http://uri.neuinfo.org/nif/nifstd/nifext_5252
ionotropic glutamate NMDA receptor | MolecularEntity | NMDA receptor | http://uri.interlex.org/ilx_0107622 | http://uri.neuinfo.org/nif/nifstd/nifext_5250
IPEROXO | MolecularEntity | iperoxo | http://uri.interlex.org/ilx_0630403 | http://id.nlm.nih.gov/mesh/2018/M000598130
Isoflurane | MolecularEntity | isoflurane | http://uri.interlex.org/ilx_0105740 | http://purl.obolibrary.org/obo/CHEBI_6015
JNK MAP kinase scaffold protein 2 | MolecularEntity | JNK MAP kinase scaffold protein 2 | null | http://purl.obolibrary.org/obo/PR_000010161
Kallikrein related-peptidase 8 | MolecularEntity | kallikrein-related peptidase 8 | null | http://purl.obolibrary.org/obo/PR_000009614
Ketamine | MolecularEntity | ketamine | http://uri.interlex.org/ilx_0105850 | https://www.drugbank.ca/drugs/DB01221
M2 receptor | MolecularEntity | muscarinic acetylcholine receptor 2 | http://uri.interlex.org/ilx_0106430 | http://uri.neuinfo.org/nif/nifstd/nifext_7946
Medetomidine | MolecularEntity | medetomidine | http://uri.interlex.org/ilx_0488544 | http://purl.obolibrary.org/obo/CHEBI_48552
muscarinic acetylcholine receptor M1 | MolecularEntity | muscarinic acetylcholine receptor 1 | http://uri.interlex.org/ilx_0106429 | http://uri.neuinfo.org/nif/nifstd/nifext_7348
muscarinic acetylcholine receptor M2 | MolecularEntity | muscarinic acetylcholine receptor 2 | http://uri.interlex.org/ilx_0106430 | http://uri.neuinfo.org/nif/nifstd/nifext_7946
muscarinic acetylcholine receptor M3 | MolecularEntity | muscarinic acetylcholine receptor 3 | http://uri.interlex.org/ilx_0106431 | http://uri.neuinfo.org/nif/nifstd/nifext_6131
NeuN | MolecularEntity | neuronal nuclear antigen | http://uri.interlex.org/ilx_0107517 | http://uri.neuinfo.org/nif/nifstd/nlx_152221
Neurobiotin | MolecularEntity | neurobiotin | http://uri.interlex.org/ilx_0107453 | http://uri.neuinfo.org/nif/nifstd/nlx_157299
Neuroligin 3 | MolecularEntity | neuroligin-3 | http://uri.interlex.org/ilx_0107485 | http://purl.obolibrary.org/obo/PR_000011256
Neuropsin promoter | MolecularEntity | kallikrein-related peptidase 8 promoter | null | null
Neurotransporter | MolecularEntity | neurotransmitter transporter | null | null
Neurotrophic factor | MolecularEntity | neurotrophic factor | null | null
nicotinic acetylcholine alpha4beta2 receptor | MolecularEntity | nicotinic receptor alpha4beta2 | http://uri.interlex.org/ilx_0597802 | http://id.nlm.nih.gov/mesh/2018/M0356600
Nop | MolecularEntity | kallikrein-related peptidase 8 | null | http://purl.obolibrary.org/obo/PR_000009614
noradrenergic receptor alpha1 | MolecularEntity | alpha-1 adrenergic receptor | null | null
noradrenergic receptor alpha2h | MolecularEntity | alpha-2H adrenergic receptor | null | null
PAI (Phthalimide-Azo-Iperoxo) | MolecularEntity | Phthalimide-Azo-Iperoxo | null | null
Parvalbumin | MolecularEntity | parvalbumin | http://uri.interlex.org/ilx_0108558 | http://uri.neuinfo.org/nif/nifstd/nifext_6
Pcp2 | MolecularEntity |   |   |  
Phaseolus vulgaris leucoagglutinin | MolecularEntity |   |   |  
Phosphodiesterases | MolecularEntity |   |   |  
Pituitary homeobox 3 promoter | MolecularEntity |   |   |  
Pitx3 | MolecularEntity |   |   |  
Prion protein promoter | MolecularEntity |   |   |  
Prnp | MolecularEntity |   |   |  
Protein Kinase A | MolecularEntity |   |   |  
Prss19 | MolecularEntity |   |   |  
Purkinje cell protein 2 promoter | MolecularEntity |   |   |  
Retrograde Tracer | MolecularEntity |   |   |  
serotonin receptor 5-HT1A | MolecularEntity |   |   |  
serotonin receptor 5-HT2 | MolecularEntity |   |   |  
Serum biomarkers from cord blood at birth | MolecularEntity |   |   |  
Serum biomarkers from mother during pregnancy | MolecularEntity |   |   |  
Somatostatin | MolecularEntity |   |   |  
Tetracycline transactivator | MolecularEntity |   |   |  
Tetracycline transactivator protein | MolecularEntity |   |   |  
tTA | MolecularEntity |   |   |  
Vasoactive intestinal peptide | MolecularEntity |   |   |  
VGLUT3 | MolecularEntity | vesicular glutamate transporter 3 | null | null
Wheat germ agglutinin-horseradish peroxidase | MolecularEntity |   |   |  
X-gal | MolecularEntity |   |   |  
3H-Oxotremorine autoradiography | MolecularEntity |   |   |  
Camk2a-tTA | MolecularEntity ORStrain |   |   |  
CaMKII-tTA | MolecularEntity ORStrain |   |   |  
EC-tTA | MolecularEntity ORStrain |   |   |  
Klk8-tTA | MolecularEntity ORStrain |   |   |  
Nop-tTA | MolecularEntity ORStrain |   |   |  
Pcp2-tTA | MolecularEntity ORStrain |   |   |  
Pitx3-tTA | MolecularEntity ORStrain |   |   |  
Prnp-tTA | MolecularEntity ORStrain |   |   |  
tTA-EC | MolecularEntity ORStrain |   |   |  
Fast blue | MolecularEntity? |   |   |  
Green beads | MolecularEntity? |   |   |  
Red beads | MolecularEntity? |   |   |  
Tet-lacZ reporter | MolecularEntity? |   |   |

**Comment by tgbugs** [comment]
A quick look suggest that most of these are correctly classified as molecular entities, however there are quite a few, such as retrograde tracer, neuropsin promoter, and others that are more correctly roles that a molecular entity can play.

**Comment by lzehl** [comment]
@tgbugs I will prepare a PR with a couple of molecular entities. Could you have a look at it once I upload the respective instances and comment on the ones that are critical (should be listed in another terminology)?

**Comment by lzehl** [comment]
this one was done in a first PR #85
